# From Local to GCS

Verificamos si tenemos pandas instalado

In [1]:
!pip freeze | grep pyarrow

'grep' is not recognized as an internal or external command,
operable program or batch file.

In [ ]:
# from google.colab import auth
# auth.authenticate_user()

Instalamos las librerías necesarias

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: tzdata in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip' command.

In [3]:
!pip install gcsfs

Collecting gcsfs
  Downloading gcsfs-2026.3.0-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.7/61.7 KB 1.6 MB/s eta 0:00:00
Requirement already satisfied: google-auth-oauthlib in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (1.2.3)
Collecting fsspec==2026.3.0
  Downloading fsspec-2026.3.0-py3-none-any.whl (202 kB)
     -------------------------------------- 202.6/202.6 KB 4.1 MB/s eta 0:00:00
Requirement already satisfied: google-cloud-storage>=3.9.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (3.10.1)
Requirement already satisfied: decorator>4.1.2 in c:\users\e.rangel\appdata\roaming\python\python311\site-packages (from gcsfs) (5.2.1)
Collecting google-cloud-storage-control
  Downloading google_cloud_storage_control-1.11.0-py3-none-any.whl (89 kB)
     ---------------------------------------- 89.7/89.7 KB 5.0 MB/s eta 0:00:00
Requirement already satisfied: google-auth>=1.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (2.40.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0
  Downloading aiohttp-3.13.5-cp311-cp311-win_amd64.whl (462 kB)
     -------------------------------------- 462.9/462.9 KB 4.2 MB/s eta 0:00:00
Requirement already satisfied: requests in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (2.32.3)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Collecting attrs>=17.3.0
  Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Collecting propcache>=0.2.0
  Using cached propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Collecting aiohappyeyeballs>=2.5.0
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Collecting aiosignal>=1.4.0
  Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting yarl<2.0,>=1.17.0
  Using cached yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (0.4.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (5.5.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (4.9.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.7.2)
Requirement already satisfied: google-api-core<3.0.0,>=2.27.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.30.3)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (1.7.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage>=3.9.0->gcsfs) (2.4.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (2025.8.3)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-auth-oauthlib->gcsfs) (2.0.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage-control->gcsfs) (0.14.4)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage-control->gcsfs) (1.74.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage-control->gcsfs) (1.26.1)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage-control->gcsfs) (6.32.0)
Requirement already satisfied: typing-extensions>=4.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (4.15.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage>=3.9.0->gcsfs) (1.70.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.49.1 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0,>=2.27.0->google-cloud-storage>=3.9.0->gcsfs) (1.74.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs) (3.3.1)
Installing collected packages: propcache, multidict, fsspec, frozenlist, attrs, aiohappyeyeballs, yarl, aiosignal, aiohttp, google-cloud-storage-control, gcsfs
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.5 aiosignal-1.4.0 attrs-26.1.0 frozenlist-1.8.0 fsspec-2026.3.0 gcsfs-2026.3.0 google-cloud-storage-control-1.11.0 multidict-6.7.1 propcache-0.4.1 yarl-1.23.0

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip' command.

In [4]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (19.0.1)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip' command.

Importamos lo necesario

In [5]:
import pandas as pd
from google.cloud import storage

In [9]:
client = storage.Client(project='project-d0c76d9f-d27a-4298-8e3')
bucket_name = 'sd-emra-gcolab-bucket-2'
bucket = client.create_bucket(bucket_name)

In [ ]:
!pwd

/content

In [10]:
columns = ['order_id', 'order_date', 'order_customer_id', 'order_status']

Subimos el archivo orders.csv o cualquier archivo csv que tengamos a la mano.

In [11]:
df = pd.read_csv('orders.csv', names=columns)
df

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [13]:
df.to_csv(
    f"gs://{bucket_name}/orders.csv",
    index=False
)

In [14]:
df.to_parquet(
    f"gs://{bucket_name}/orders.parquet",
    index=False
)

In [15]:
df_parquet = pd.read_parquet(f"gs://{bucket_name}/orders.parquet")
df_parquet

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [16]:
df_csv = pd.read_csv(f"gs://{bucket_name}/orders.csv", names=columns)
df_csv

       order_id             order_date  order_customer_id     order_status
0      order_id             order_date  order_customer_id     order_status
1             1  2013-07-25 00:00:00.0              11599           CLOSED
2             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
3             3  2013-07-25 00:00:00.0              12111         COMPLETE
4             4  2013-07-25 00:00:00.0               8827           CLOSED
...         ...                    ...                ...              ...
68879     68879  2014-07-09 00:00:00.0                778         COMPLETE
68880     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68881     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68882     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68883     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68884 rows x 4 columns]